import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        surface: "var(--surface)",
        ink: "var(--ink)",
        "ink-soft": "var(--ink-soft)",
        "ink-faint": "var(--ink-faint)",
        accent: "var(--accent)",
        "accent-soft": "var(--accent-soft)",
        border: "var(--border)",
        "border-md": "var(--border-md)",
        "adm-bg": "var(--adm-bg)",
        "adm-surface": "var(--adm-surface)",
        "adm-border": "var(--adm-border)",
        "adm-sidebar": "var(--adm-sidebar)",
        "adm-sidebar-text": "var(--adm-sidebar-text)",
        /* Olly landing (requires `.olly-landing` ancestor) */
        olly: {
          primary: "var(--color-primary)",
          "primary-hover": "var(--color-primary-hover)",
          "brand-mid": "var(--color-brand-400)",
          accent: "var(--color-accent)",
          "accent-hover": "var(--color-accent-hover)",
          "lime-cta": "var(--color-lime-cta)",
          "lime-cta-hover": "var(--color-lime-cta-hover)",
          "gray-0": "var(--color-gray-0)",
          "gray-200": "var(--color-gray-200)",
          "gray-300": "var(--color-gray-300)",
          "gray-400": "var(--color-gray-400)",
          "gray-500": "var(--color-gray-500)",
          "gray-600": "var(--color-gray-600)",
          "gray-800": "var(--color-gray-800)",
          "gray-900": "var(--color-gray-900)",
          "gray-950": "var(--color-gray-950)",
          "gray-1000": "var(--color-gray-1000)",
          canvas: "var(--color-bg)",
          surface: "var(--color-surface)",
          "surface-2": "var(--color-surface-2)",
          line: "var(--color-border)",
          ink: "var(--color-text)",
          bright: "var(--color-text-bright)",
          muted: "var(--color-text-muted)",
          dim: "var(--color-text-dim)",
          "form-pill": "var(--color-form-pill)",
          "chat-user": "var(--color-chat-user)",
          "chat-user-ink": "var(--color-chat-user-ink)",
          "step-line": "var(--color-step-border)",
          danger: "var(--color-danger)",
        },
      },
      maxWidth: {
        "olly-container": "var(--olly-container-max)",
        "olly-phone": "20rem",
        "olly-mock": "28rem",
        "olly-coach": "17rem",
        "olly-orbit": "36rem",
        "olly-hero-orbit": "22rem",
        "olly-hero-orbit-md": "32rem",
      },
      boxShadow: {
        "olly-sm": "var(--shadow-sm)",
        "olly-md": "var(--shadow-md)",
        "olly-lg": "var(--shadow-lg)",
        "olly-glow": "var(--shadow-glow)",
      },
      ringColor: {
        "olly-primary": "var(--color-primary)",
      },
      transitionDuration: {
        olly: "var(--olly-duration)",
      },
      fontFamily: {
        display: ["var(--font-display)", "Impact", "sans-serif"],
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
        "olly-sans": ["var(--font-olly-sans)", "system-ui", "sans-serif"],
      },
      spacing: {
        "space-0": "var(--space-0)",
        "space-1": "var(--space-1)",
        "space-2": "var(--space-2)",
        "space-3": "var(--space-3)",
        "space-4": "var(--space-4)",
        "space-5": "var(--space-5)",
        "space-6": "var(--space-6)",
        "space-7": "var(--space-7)",
        "space-8": "var(--space-8)",
        "space-9": "var(--space-9)",
        "space-10": "var(--space-10)",
        "space-11": "var(--space-11)",
        "space-12": "var(--space-12)",
        /* Olly scale (scoped vars on `.olly-landing`) */
        "olly-1": "var(--olly-space-1)",
        "olly-2": "var(--olly-space-2)",
        "olly-3": "var(--olly-space-3)",
        "olly-4": "var(--olly-space-4)",
        "olly-5": "var(--olly-space-5)",
        "olly-6": "var(--olly-space-6)",
        "olly-7": "var(--olly-space-7)",
        "olly-8": "var(--olly-space-8)",
        "olly-10": "var(--olly-space-10)",
        "olly-12": "var(--olly-space-12)",
        "olly-14": "var(--olly-space-14)",
        "olly-16": "var(--olly-space-16)",
        "olly-20": "var(--olly-space-20)",
        "olly-24": "var(--olly-space-24)",
        "olly-32": "var(--olly-space-32)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
        btn: "var(--btn-radius)",
        "olly-sm": "var(--radius-sm)",
        "olly-md": "var(--radius-md)",
        "olly-lg": "var(--radius-lg)",
        "olly-xl": "var(--radius-xl)",
        "olly-full": "var(--radius-full)",
      },
      transitionTimingFunction: {
        ease: "cubic-bezier(.4,0,.2,1)",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(14px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        fadeUp: "fadeUp .38s ease both",
      },
    },
  },
  plugins: [],
};

export default config;
